# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hummy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hummy.Delivery')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hummy.Meal')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='deliverymeal',
            unique_together=set([('meal', 'delivery')]),
        ),
    ]
