# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hummy', '0002_auto_20160921_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='state',
            field=models.CharField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=20),
        ),
    ]
