# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hummy', '0003_delivery_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='state',
            new_name='status',
        ),
    ]
